### ISSUE TITLE
Judging floating point numbers cannot use constant equal sign

### ISSUE THREAD

**Issue by jinzhu1911** [JSBSim-Team/jsbsim#102]
In Class FGColumnVector3, in the function of Overload constant equal sign whitch it uses "==" to judge double, I think this is not right.

**Comment by bcoconni** [comment]
I'm not sure I'm getting your point: your statement is too vague. Can you please point at a place in the code where you think the usage of `==` is *"not right"* ?

**Comment by bcoconni** [comment]
Ping !

@jinzhu1911 It's been one month since I asked you some clarifications but got no answer. Could you please be more specific ?

**Comment by bcoconni** [comment]
Last call before ~departure~ closing the issue as **won't fix** :smiley:

**Comment by jinzhu1911** [comment]
in the function Comparison operator.
 bool operator==(const FGColumnVector3& b) const {
    return data[0] == b.data[0] && data[1] == b.data[1] && data[2] == b.data[2];
  }

**Comment by agodemar** [comment]
@jinzhu1911 Your answer isn't clear. Could you elaborate?
Please, do keep in mind that this is not the place to be cryptic.

**Comment by jinzhu1911** [comment]
in the function Comparison operator.
 bool operator==(const FGColumnVector3& b) const {
    return data[0] == b.data[0] && data[1] == b.data[1] && data[2] == b.data[2];
  }


> 
> 
> I'm assuming he means the method should be along the following lines:
> 
> ```c++
> bool operator==(const FGColumnVector3& b) const {
>    return fabs(data[0] - b.data[0]) < 1e-13 && fabs(data[1] - b.data[1]) < 1e-13 && 
>       fabs(data[2] - b.data[2]) < 1e-13;
> }
> ```
Yes, I mean this. Thanks very much!
