### ISSUE TITLE
How Jsbsim models the "+" shaped tail fins of missiles and rockets.

### ISSUE THREAD

**Issue by ASh-en** [JSBSim-Team/jsbsim#1062]
### Discussed in https://github.com/JSBSim-Team/jsbsim/discussions/1060

<div type='discussions-op-text'>

<sup>Originally posted by **ASh-en** March 28, 2024</sup>
Hello everyone, I would like to confirm whether \<htailarea>,  \<htailarm> , \<vtailarea>, \<vtailarm>  can also model the "+" tail fins of missiles and rockets. and also how to model aircraft with "+" shaped wings? And how to establish the relationship between $δ_x$, $δ_y$, $δ_z$ and the attitude of the aircraft?</div>

**Comment by seanmcleod** [comment]
This is not a bug report or feature request. So deleting this issue. Discussion can continue in the discussion item you created originally.
