### ISSUE TITLE
aerodynamics_2_graphviz

### ISSUE THREAD

**Issue by yanzixiang** [JSBSim-Team/jsbsim#1125]
hello,everyone,I am a newbie to jsbsm,
i want to analyse the aerodynamics of an aircraft using graphviz,
but jsbsim sames have NOT export this kind of information out,
so i add some function and variable,
and use the [gvpp ](https://github.com/compilin/gvpp/) to export an dot,
like this.
I am a newbie to cmake ,too,
I make two project using Virtual Studio,
one called jsbsim_static,
another one called aerodynamics_2_graphviz,
I got the result like this.

![f16_1](https://github.com/user-attachments/assets/c97add0f-a85c-44c4-9bf1-ebc3c951ef87)
![f16_2](https://github.com/user-attachments/assets/d0222472-3856-46ef-afa7-0219b6b21fe4)
![f16_3](https://github.com/user-attachments/assets/87a665d5-de1b-4ca1-94ae-1df5998added)
![f16_4](https://github.com/user-attachments/assets/7bd0087a-d0a9-4f6b-83b3-223bcd2b95db)
![f16_5](https://github.com/user-attachments/assets/59eaa8f7-2b2f-493d-9950-2dbb5027944f)
![f16_6](https://github.com/user-attachments/assets/f650f90d-cb98-4f90-919b-15612b3a513d)

I think maybe this can help someone else, a little.
I wish someone can help to write an "CMakeLists.txt" for them.

**Comment by seanmcleod** [comment]
> i want to analyse the aerodynamics of an aircraft using graphviz,

What sort of analysis are you trying to perform? And how do these graphs help in that?

**Comment by yanzixiang** [comment]
> > i want to analyse the aerodynamics of an aircraft using graphviz,
> 
> What sort of analysis are you trying to perform? And how do these graphs help in that?

the full equation, which parameter is counted in the axis force calculation,
seems very hard to understand.

the pictures are made by analysing the aerodynamics of aircraft included in jsbsim,f16,
![1721532057894](https://github.com/user-attachments/assets/8518697f-23f9-44cc-a84d-b010dc3062c7)
the left labels refer to the functions defined here
![1721532192648](https://github.com/user-attachments/assets/ae70ff9c-8502-4dcf-9ed8-13af0d76c261)

**Comment by seanmcleod** [comment]
When I looked at the visual graphs I must say I thought they were harder to read than the actual XML in the aerodynamics section.

If you want a more compact summary wouldn't something like this be better/easier to read? Basically a summary getting rid of all the XML tags etc. and also not showing the contents of `Table` elements.

```
aero/coefficient/CDDh  (Drag_due_to_horizontal_tail_deflection)
   - aero/qbar-psf
   - metrics/Sw-sqft
   - Table
      - aero/alpha-rad
      - fcs/elevator-pos-rad

aero/coefficient/CDmach  (Drag_due_to_mach)
   - aero/qbar-psf
   - metrics/Sw-sqft
   - Table
      - velocities/mach

aero/coefficient/CDDlef  (Drag_due_to_leading_edge_flap_deflection)
   - aero/qbar-psf
   - metrics/Sw-sqft
   - fcs/lef-pos-rad
   - Table
      - aero/alpha-rad
....
....
```

Ideally maybe with an option with a link to graph renderings of tables using something like this - https://github.com/NikolaiVChr/jsb-to-png

**Comment by yanzixiang** [comment]
> When I looked at the visual graphs I must say I thought they were harder to read than the actual XML in the aerodynamics section.
> 
> If you want a more compact summary wouldn't something like this be better/easier to read? Basically a summary getting rid of all the XML tags etc. and also not showing the contents of `Table` elements.

your way can just follow the way from aero/coefficient/CDDh to aero/qbar-psf,metrics/Sw-sqft,aero/alpha-rad,fcs/elevator-pos-rad....
sometimes, people like me want to think in the opposite direction,
what does fcs/elevator-pos-rad change and effect the aerodynamic axis

> Ideally maybe with an option with a link to graph renderings of tables using something like this - https://github.com/NikolaiVChr/jsb-to-png

yes, that is just what i am trying to do....

**Comment by seanmcleod** [comment]
> sometimes, people like me want to think in the opposite direction,

Yep, I read/looked at the graphs from left to right and followed the direction of the arrows.

> what does fcs/elevator-pos-rad change and effect the aerodynamic axis

Hmm, given the number of crisscrossing lines etc. again I must say that for me trying to read and follow the graph is harder than either scanning the summary example I gave above, or having the summary tool allow you to select a parameter, e.g. `fcs/elevator-pos-rad` and then filter the list of functions that use it etc.

Not saying that no-one will find these graphs useful, just for me personally so far I find them more difficult to read.

**Comment by yanzixiang** [comment]
> > Ideally maybe with an option with a link to graph renderings of tables using something like this - https://github.com/NikolaiVChr/jsb-to-png
> 
> yes, that is just what i am trying to do....

i add the option for embbing the jsb-to-png image of an table,
and get this.

the number of crisscrossing lines is depending on the complexity of the aerodynamics,
maybe the appearance of the graphs is not so good,
but it is necessary to give people the possiblity to get the information of the aerodynamics,
and make better graphs....

![test_5](https://github.com/user-attachments/assets/56c98d34-899f-42f0-8e79-cface5c30bd1)
![test_0](https://github.com/user-attachments/assets/ec6f03bf-3ea1-4510-a3a9-79810d1b711b)
![test_1](https://github.com/user-attachments/assets/5bbb320a-3854-417b-9c90-8398e5740459)
![test_2](https://github.com/user-attachments/assets/fb04db1d-4878-4806-90cc-50bb806fd600)
![test_3](https://github.com/user-attachments/assets/c3565caf-b8b7-4933-a074-4fb01f144136)
![test_4](https://github.com/user-attachments/assets/b948f842-a4ac-40b5-bdf7-f1ab332a0b7d)

**Comment by agodemar** [comment]
@yanzixiang @seanmcleod 
I like the effort to transform the XML into something visual. It can become a piece of software that goes in the `utils` section, besides `aeromatic`.

**Comment by seanmcleod** [comment]
@agodemar there are a some comments from @bcoconni and myself in the pull request - https://github.com/JSBSim-Team/jsbsim/pull/1126
