### ISSUE TITLE
Expose air-fuel ratio of Piston engine to the property tree

### ISSUE THREAD

**Issue by agodemar** [JSBSim-Team/jsbsim#116]
*From: Alan Teeder*
A user on the FG forum [asks to have air-fuel ratio of Piston engine exposed](https://forum.flightgear.org/viewtopic.php?f=66&t=34762&sid=3ccba873d448bf34b9e84c643ab8a50b&p=336225#p336225) so that he can trigger exhaust smoke with an over-rich mixture.

**Comment by seanmcleod** [comment]
Alan you mentioned in the FlightGear forum that there is some commented out code in FGPiston.cpp to calculate the AFR (Air Fuel Ratio). I presume you're referring to the following?

```c++
/**
 * Calculate the fuel flow into the engine.
 *
 * Inputs: Mixture, thi_sea_level, p_amb, m_dot_air
 *
 * Outputs: equivalence_ratio, m_dot_fuel
 */

void FGPiston::doFuelFlow(void)
{
  double thi_sea_level = 1.3 * in.MixturePos[EngineNumber]; // Allows an AFR of infinity:1 to 11.3075:1
  equivalence_ratio = thi_sea_level * 101325.0 / p_amb;
//  double AFR = 10+(12*(1-in.Mixture[EngineNumber]));// mixture 10:1 to 22:1
//  m_dot_fuel = m_dot_air / AFR;
  m_dot_fuel = (m_dot_air * equivalence_ratio) / 14.7;
  FuelFlowRate =  m_dot_fuel * 2.2046;  // kg to lb
  if(Starved) // There is no fuel, so zero out the flows we've calculated so far
  {
    equivalence_ratio = 0.0;
    FuelFlowRate = 0.0;
    m_dot_fuel = 0.0;
  }
  FuelFlow_pph = FuelFlowRate  * 3600;
  FuelFlow_gph = FuelFlow_pph / FuelDensity;
}
```

So in theory we could just uncomment the AFR calculation and expose it via the property tree?

**Comment by alanjt** [comment]
The forum post has turned into one of those squabbles about something unrelated,  3 pages of it so far, and none of it about the original request.........
The OP (who is not involved in the rants)  wants it so that he can trigger smoke when the mixture is over rich. No doubt there will be other uses.
Alan

**Comment by bcoconni** [comment]
@seanmcleod 
> So in theory we could just uncomment the AFR calculation and expose it via the property tree?

No by definition the AFR is the ratio of the air mass flow to the fuel mass flow which is `14.7/equivalence_ratio` given the line of code below
```c++
m_dot_fuel = (m_dot_air * equivalence_ratio) / 14.7;
```
I think the lines above have been commented out because they have been superseded by this code.

**Comment by seanmcleod** [comment]
I've submitted a pull request https://github.com/JSBSim-Team/jsbsim/pull/118 to expose an Air Fuel Ratio (AFR) property for piston engines.

**Comment by seanmcleod** [comment]
I decided to compare the engine power output versus AFR.

![image](https://user-images.githubusercontent.com/824856/45500998-55530080-b780-11e8-9809-f817cec11f15.png)

I used the C172p aircraft model at sea-level with the engine running and brakes on and `fcs\throttle-cmd-norm = 1` and then ramped the `fcs/mixture-cmd-norm from 1.3 down to 0.7`.

To compare against the Wikipedia graph:

![image](https://user-images.githubusercontent.com/824856/45501172-ca263a80-b780-11e8-90f0-60bf5f9d4f33.png)

**Comment by seanmcleod** [comment]
Just wondering whether the power peak appearing so far left around an AFR of 10 is related to this issue - https://github.com/JSBSim-Team/jsbsim/issues/96 ?

**Comment by bcoconni** [comment]
I have just pushed JSBSim bleeding edge to FlightGear so this new AFR feature is available there.

**Comment by alanjt** [comment]
Many thanks for this. I have updated the forum thread.
Alan

**Comment by legoboyvdlp** [comment]
To implement something such as spark plug fouling  (https://www.simcoders.com/2016/06/02/20160602keep-your-spark-plugs-clean/)

is AFR the ratio that I want? So if AFR is less than 15, the spark plugs should begin to foul (slowly - maybe quicker at AFR of ~10)?
