### ISSUE TITLE
Sensor element: fail_stuck behaviour

### ISSUE THREAD

**Issue by legoboyvdlp** [JSBSim-Team/jsbsim#119]
Hi,
I'm trying to replicate the Air Data Reference Unit of the A320 using JSBSIM <sensor> elements. 

![image](https://user-images.githubusercontent.com/10434911/45510098-2a24dd00-b791-11e8-9335-47748fe25970.png)
I set fail_stuck to 1.0. 
I expected the speed to get stuck at 74.5 knots, instead it actually went to 0. Is this intended behaviour?

Thanks,
Jonathan

**Comment by legoboyvdlp** [comment]
This might help:
https://en.wikipedia.org/wiki/Pitot-static_system#Pitot-static_errors

**Comment by seanmcleod** [comment]
If you want to model the blocked pitot tube case and the blocked static port case then you'll need 2 sensor elements, 1 to model the pitot sensor and 1 to model the static port and you would then set `fail_stuck` on the relevant sensor and you would need to calculate the airspeed using the 2 sensors.

In other words you can't have a single sensor element representing an airspeed indicator and then set `fail_stuck` on that and assume you can model the blocked pitot and blocked static cases. In this case you would only be modeling the airspeed indicator/computer itself failing/getting stuck.

**Comment by legoboyvdlp** [comment]
`So at first glance it looks like fail_stuck should output the last sensor input. However PreviousOutput is only set in the Lag() method. So if you haven't configured any lag parameters, hence the reason I was asking how you had set things up, then PreviousOutput will always be 0, it's initialized value on sensor element creation.

So this does seem to be a bug in the FGSensor class.`

Ah - that's exactly right, I'm not using Lag! Thanks :)

**Comment by seanmcleod** [comment]
> Ah - that's exactly right, I'm not using the lag parameters at all! That would explain it.

But it's still a bug since you shouldn't be **required** to use lag, but adding some lag, even very minimal, is a work around for now.

**Comment by bcoconni** [comment]
The problem should now be fixed by commit f543d63.
@legoboyvdlp 
Please test and let me know if that fixes the issue on your side as well.

**Comment by bcoconni** [comment]
@legoboyvdlp 
If you are testing with FlightGear, the bug fixes have just been pushed to FlightGear source code.

**Comment by legoboyvdlp** [comment]
Great!

May I ask if the fgturbine fixes I did were pushed?

**Comment by bcoconni** [comment]
> May I ask if the fgturbine fixes I did were pushed?

Yes they will be pushed in a separate commit because bug fixes could make their way to the release 2018.3 of FlightGear while new features are intended to stay in the branch `next` until the next release.

The commit in question should be pushed to FlightGear today.

**Comment by legoboyvdlp** [comment]
Thanks!

**Comment by bcoconni** [comment]
@legoboyvdlp 
Have you had the opportunity to check if the bug you reported in this issue is fixed ? The fix has been pushed in FlightGear 2018.3 and in its `next` branch

**Comment by legoboyvdlp** [comment]
Thanks! No, I haven't - I've been busy elsewhere. I can check in a few days.

**Comment by bcoconni** [comment]
@legoboyvdlp 
> No, I haven't, sorry - I've been busy elsewhere. I can check in a few days.

Have you had the opportunity to check if the bug you reported in this issue is fixed ?

**Comment by legoboyvdlp** [comment]
again I've been quite busy. but if its in 2018.3, then I suppose I can check right now

**Comment by bcoconni** [comment]
OK thanks. Issue closed.
