### ISSUE TITLE
Is there a way to initialize in the air and cruise normally？

### ISSUE THREAD

**Issue by cx-zzz** [JSBSim-Team/jsbsim#1195]
### Discussed in https://github.com/JSBSim-Team/jsbsim/discussions/1192

<div type='discussions-op-text'>

<sup>Originally posted by **cx-zzz** November 21, 2024</sup>
Hi, i am new to JSBSim and would like to know if it is possible to initialize A320 in JSBSim in the air like normally flying? 
I have see the issue [298](https://github.com/JSBSim-Team/jsbsim/issues/298) and tried to  change xml file, but the aircraft was just located at the position i set, but the parameter like throtle was just 0. 
Is there any way to achieve this？</div>

**Comment by bcoconni** [comment]
Closed because redundant with discussion #1192.
@cx-zzz, please don't duplicate discussions as an issue, thanks.
