### ISSUE TITLE
Class hierarchy diagrams and basic class documentation

### ISSUE THREAD

**Issue by agodemar** [JSBSim-Team/jsbsim#12]
We need diagrams of the up-to-date class hierarchy in JSBSim.
If someone did ever generate in the past a set of documentation files (Doxigen?), this is a good chance to revamp the procedure.
Class hierarchy graphics will go into the *Programmer's Manual* as well.

**Comment by bcoconni** [comment]
The class hierarchy diagram is automatically generated by JSBSim Doxygen docs. It is available at https://jsbsim-team.github.io/jsbsim/inherits.html

Note that each time a commit is pushed this diagram is updated by Travis CI.

**Comment by agodemar** [comment]
Great, thanks!
