### ISSUE TITLE
Brakes and static force

### ISSUE THREAD

**Issue by legoboyvdlp** [JSBSim-Team/jsbsim#130]
Hi,
Many users are tuning brakes using <static_friction> - this results in correct braking behaviour, but really seems to mess up steering - is it possible to have a property that tunes the brake force without affecting the static friction of the wheels ( resistance to lateral force if I remember right? )

**Comment by bcoconni** [comment]
@legoboyvdlp 
This topic is currently being discussed in the issue #127.
Thanks to post your comments/question in that other issue.

This topic is closed as a duplicate of #127.

**Comment by legoboyvdlp** [comment]
Thanks!
