### ISSUE TITLE
As Massbalance execute before Propulsion,  the TankInertia is not in the same CG with basJ.

### ISSUE THREAD

**Issue by jinzhu1911** [JSBSim-Team/jsbsim#131]
In the function Run of FGMassBlance ,  use statement "GetPointmassInertia( lbtoslug * EmptyWeight, vbaseXYZcg )" to transfer the baseJ to the new CG, but in the statement "mJ += in.TankInertia" which TankInerita is calculated in the old CG.
Thanks for your help!

**Comment by bcoconni** [comment]
> in the statement `mJ += in.TankInertia` which TankInerita is calculated in the old CG.

That's correct. Not sure this makes much difference since the CG position is changing very slowly but strictly speaking you are correct.

If you need higher precision for your application, feel free to submit a patch.

**Comment by bcoconni** [comment]
No feedback for 3 months. Issue closed.
