### ISSUE TITLE
make calculation for each "dt" 

### ISSUE THREAD

**Issue by alexandrequ** [JSBSim-Team/jsbsim#156]
hello, 
In my xml script for each step of time , I would like to call a C++ function who calculates the wind velocity and use the function outputs to apply them here in the xml code : 
`      <set name="atmosphere/wind-east-fps" action="FG_RAMP" value="OUTPUT1" tc="10.0"/>`
      `<set name="atmosphere/wind-down-fps" action="FG_RAMP" value="OUTPUT2" tc="10.0"/>`
      `<set name="atmosphere/wind-north-fps" action="FG_RAMP" value="OUTPUT3" tc="10.0"/> `
does someone have an idea ?
With regards,

alex

**Comment by bcoconni** [comment]
@alexandrequ 
This is the third issue (#132, #142 and now this one) opened about the same topic: "how to connect JSBSim with an external program that generate wind data". You opened #142 and #156 and participated to #132. 

Perhaps, you are finding that you do not get answers quick enough and we are sorry about that. If you feel that your questions are not addressed or left aside then please tell us in the original issue #142.

Duplicating issues on the same topic is definitely not the way to get more (positive) attention.

This topic is closed as a duplicate.
