### ISSUE TITLE
Updating release label to v2019a

### ISSUE THREAD

**Issue by agodemar** [JSBSim-Team/jsbsim#166]
Should we mark our release assets as *v2019a*?
The issue with the non-changing date of future releases will still be there. At least we manually mark the right year on the binaries we produce.
Makes sense?
@bcoconni @seanmcleod

**Comment by bcoconni** [comment]
Makes sense.

This might also be the opportunity to drop Ubuntu Trusty in favor of Ubuntu Xenial which is now supplied by Travis CI.

**Comment by agodemar** [comment]
> This might also be the opportunity to drop Ubuntu Trusty in favor of Ubuntu Xenial which is now supplied by Travis CI.

Yes, sure.

**Comment by bcoconni** [comment]
Done (including switching to Ubuntu Xenial).
