### ISSUE TITLE
Parsing behaviour of extraneous <property> inside an auto value/property element

### ISSUE THREAD

**Issue by Zaretto** [JSBSim-Team/jsbsim#182]
With the current changes to the XML parser the following (invalid) statement no longer works; I suspect that previously the `<property>` tags on the `max` operator were simply being ignored.

```      <clipto>
        <min> 0 </min>
        <max><property>systems/hydraulics/normal-pressure</property></max>
      </clipto>
```
what I really meant of course is the following;
```     <clipto>
        <min> 0 </min>
        <max>systems/hydraulics/normal-pressure</max>
      </clipto>
```
Can we make this a syntax validation failure please.

**Comment by bcoconni** [comment]
This has been added in commit 61030f0.

**Comment by bcoconni** [comment]
And this is now available in FlightGear `next` branch.

**Comment by bcoconni** [comment]
@Zaretto 
Have you had the opportunity to test that feature in FlightGear ?

**Comment by Zaretto** [comment]
I've tested it and it worked fine.

Thanks for doing this.
