### ISSUE TITLE
Actuator crash - hardover

### ISSUE THREAD

**Issue by legoboyvdlp** [JSBSim-Team/jsbsim#200]
Hi,
If I set a hardover fail and no minimum value is set, FlightGear crashes. Perhaps a nil check is needed on line 159 of FGActuator?

  if (fail_hardover) Input = Input < 0.0 ? ClipMin->GetValue() : ClipMax->GetValue();

**Comment by bcoconni** [comment]
I pushed a tentative fix to FlightGear. Let me know if that fixes the problem.

**Comment by legoboyvdlp** [comment]
Hi,
Thank you!

**Comment by legoboyvdlp** [comment]
I have compiled last night and hope to try it today. Sorry for the delay.

**Comment by legoboyvdlp** [comment]
Unfortunately not, it still crashes.

**Comment by bcoconni** [comment]
OK I'll investigate further.

**Comment by bcoconni** [comment]
> Unfortunately not, it still crashes.

That's strange, according to the regression test added by the commit e743b3b, the bug is now fixed. Are you sure you have tested the last version of FlightGear ?

**Comment by legoboyvdlp** [comment]
Hmm - I think so, but perhaps my compiler was misbehaving. I will try it again.

**Comment by bcoconni** [comment]
> Also, surely a hardover means not the neutral position but the minimum or maximum position is reached and the actuator sticks there? Did I misunderstand the test?

No but for that to happen you need to specify the minimum and maximum position i.e. you need to define a `<clipto>` element such as
https://github.com/JSBSim-Team/jsbsim/blob/de6bbb1fa0785142dafe5eb3825967d28bd641d7/aircraft/c172x/c172x.xml#L355-L366
If the element `<clipto>` is missing then the actuator goes to its neutral position for the lack of  better option.

**Comment by mike402** [comment]
I thought actuators, integrators etc didn't respect `<clipto>` internally and just silently kept going beyond the value?

**Comment by bcoconni** [comment]
> I thought actuators, integrators etc didn't respect `<clipto>` internally and just silently kept going beyond the value?

**????**
Where this assumption is coming from ? Have you experienced some cases where `<clipto>` was ignored ? In that case this should be reported as a bug.

**Comment by mike402** [comment]
~~~
 <property>asdf/inp</property>
 <channel name="Test">

  <integrator name="asdf/int_clip">
   <output>asdf/int_clip_</output>
   <input>asdf/inp</input>
   <c1>1.0</c1>
   <clipto>
    <min>-1.0</min>
    <max>1.0</max>
   </clipto>
  </integrator>

  <integrator name="asdf/int">
   <output>asdf/int_</output>
   <input>asdf/inp</input>
   <c1>1.0</c1>
  </integrator>

  <actuator name="asdf/act_clip">
   <output>asdf/act_clip_</output>
   <input>asdf/inp</input>
   <rate_limit>1.0</rate_limit>
   <clipto>
    <min>-1.0</min>
    <max>1.0</max>
   </clipto>
  </actuator>

  <actuator name="asdf/act">
   <output>asdf/act_</output>
   <input>asdf/inp</input>
   <rate_limit>1.0</rate_limit>
  </actuator>

 </channel>
~~~

1. Set asdf/inp to 10 and wait for some time, the unclipped integrator and actuator will go beyond the <clipto> values.
2. Set asdf/inp to -10.

Expectation: clipped integrator and actuator would immediately start going back from their limit.

Reality: they stay in sync with the unclipped versions, indicating that clipto is not respected by internal logic and just clips the output.

**Comment by bcoconni** [comment]
@mike402 
I'll investigate that. Meanwhile would you mind opening a new issue about that topic and delete your post above to avoid polluting the topic from @legoboyvdlp ?

Thanks.

**Comment by mike402** [comment]
No problem, I moved the post.

**Comment by bcoconni** [comment]
@legoboyvdlp, have you come to a conclusion regarding to this issue ?

**Comment by legoboyvdlp** [comment]
No, sorry.

**Comment by bcoconni** [comment]
@legoboyvdlp 
Have you had the opportunity to check if that issue is fixed ?

**Comment by legoboyvdlp** [comment]
Yeah it goes to value 0 now when I set hardover.

Sorry, this was long overdue, my apologies.
