### ISSUE TITLE
How to modify output data?

### ISSUE THREAD

**Issue by hovick** [JSBSim-Team/jsbsim#207]
Hi all, I am kind of new to JSBSIM and programming in general. I have created a script of a c172x going throught several waypoints. I am trying to modify the output data but so far no luck. What I am trying to change is the output data "JSBout172B.csv", right now the output shows velocity, acceleration etc columns every 0.1 sec. I am pretty sure this may be easily changed by turning off the output variables and the rate of the output; ex

`     <output name="JSBout172B.csv" type="CSV" rate="10">
       <velocities> ON        </velocities>`
`     <output name="JSBout172B.csv" type="CSV" rate="**100**">
        <velocities> **OFF**        </velocities>`

I have already tried changing these variables in the "c172x.xml, output.xml" at aircraft folder, "velocities.xml; aerodynamics.xml..." at the data_output folder and "JSBSim.xsd" but so far no luck, the output data remains the same.
Could anyone tell me where do I have to change the code in order to obtain different output data log in the JSBout172B.csv file? 
Thanks!

**Comment by hovick** [comment]
Ok, I have tried again by completely eliminating the code lines wich I dont want such as
`<velocities> ON </velocities>` and it worked
Before I simply changed these functions to description text by adding  however it wouldnt affect the output..not sure why, any ideas?
I now want to change the columns of each property that appear, lets say for the massprops property, I'd like to remove I_{xx} & I_{xy} columns but maintain the I_{xz}

**Comment by seanmcleod** [comment]
You can use a combination of individual properties e.g.

```      
<property> accelerations/udot-ft_sec2 </property>
<property> accelerations/vdot-ft_sec2 </property>
```
and/or 'macros' like `<rates>`, `<forces>` etc. which output a pre-set set of properties.

```
<rates> ON </rates>
<forces> ON </forces>
```

**Comment by bcoconni** [comment]
@hovick Do you consider your question answered ? If so, can we close this issue ?

**Comment by bcoconni** [comment]
Issuer is not responding. Issue closed.
