### ISSUE TITLE
Electric motor RPM (useful for Ardupilot etc)

### ISSUE THREAD

**Issue by javaanchahl** [JSBSim-Team/jsbsim#229]
It would seem to be harmless to everyone, and useful to some, especially in the drone community to provide an RPM for electric aircraft.

In src/input_output/FGfdmSocket.cpp, ca. line 50
`#include "models/propulsion/FGElectric.h"`
and at Line 244 
` case (FGEngine::etElectric):
      net->rpm[i]       = (float)(((FGElectric *)Propulsion->GetEngine(i))->getRPM());
      break;`

unless there is a good reason not to?

**Comment by bcoconni** [comment]
I think you are referring to the file `src/input_ouput/FGOutputFG.cpp`  line 244 ?
https://github.com/JSBSim-Team/jsbsim/blob/4840a621dafe1ce64970990ddaec3e86a1c7e082/src/input_output/FGOutputFG.cpp#L244-L245
If that is so, the change you are proposing can be included in JSBSim. You are welcome to submit a pull request with your change.

**Comment by bcoconni** [comment]
@javaanchahl I pushed the change you suggested in JSBSim via the commit 4b10d37.
Let me know if you get the expected result.

**Comment by javaanchahl** [comment]
Arduplane SITL now reports RPM for electrics when connected to JSBSim, in
ArduPlane the RPM_TYPE parameter must be set to 2.

**Comment by bcoconni** [comment]
So shall we consider the issue closed ?

**Comment by javaanchahl** [comment]
Yes.
Thanks very much.

Regards
Javaan
