### ISSUE TITLE
Turbine: ignitionn2

### ISSUE THREAD

**Issue by NikolaiVChr** [JSBSim-Team/jsbsim#233]
Hey, I have a turbine in FG 2019.1

When I set ignitionn2 N2 still goes to 25.18, but N1 goes to what ignitionn2 is set it to, has this been fixed in later JSBSim versions?

I just read the code:
if (el->FindElement("ignitionn2"))
    IgnitionN1 = el->FindElementValueAsNumber("ignitionn2");

**Comment by legoboyvdlp** [comment]
oops...
