### ISSUE TITLE
In FGFS Start running JSBSim on explicit command ...

### ISSUE THREAD

**Issue by abassign** [JSBSim-Team/jsbsim#237]
In FGFS there is a property that lets you know the initial configuration required, this property is **/sim/preset** Knowing this during the start of JSBSim allows you to correctly configure the simulator, for example having the landing gear extracted if the start of the simulation is with airplane on the ground or the landing gear closed if the start of the simulation is in flight.
The reason I can't read these initial properties is due to the fact that JSBSim starts much earlier than the programs that generate these properties. The solution I propose is not to run JSBSim if a property, which I choose, does not have the value true. In fact this property acts as a synchronization system. If the property does not exist JSBSim must wait, but not report an error, since it means that FGFS is still initializing. If the property is not defined in JSBSim the behavior of the program remains the current one. During the execution of the program, if the property is reported in False, JSBSim stops again.
This change would solve a very frustrating problem: in some cases JSBSim does not read the initial state of FGFS.
What do you think ?
Looking at the code, it does not seem problematic to change the code to get this function.

**Comment by bcoconni** [comment]
I am really struggling to see why this feature should be added to JSBSim. If the initialization of JSBSim should be deferred until something else happens in FGFS then it is an issue with FGFS. Please discuss this issue with the FlightGear developers.
