### ISSUE TITLE
JSBSim fails to get host by number for flightgear port over LAN when run in WSL

### ISSUE THREAD

**Issue by brisk0** [JSBSim-Team/jsbsim#247]
Problem
---------
JSBSim reports "Could not get host address by number..." instead of sending packets when attempting to output using flightgear protocol

Set-up / Testing
----------------
I am running an aircraft including the line:
    `<output name="{LAN ipv4 address of host computer}" type="FLIGHTGEAR" port="7127" protocol="UDP" rate="200"/>`
Tested by having the host computer (at address listed) running `ncat -l -u -p 7127`
Data was sent successfully using `nc -u {host LAN address} 7127`
JSBSim running on the same machine reports "Could not get host net address by number..."
Tested running JSBSim through ardupilot SITL integration and running JSBSim directly (compiled from source) using the same aircraft file.

Environment
-------------
WSL running Ubuntu 18.04 (bionic) on Windows 10
Local area network on WiFi, private network with firewall off
Host computer running Windows 10 (no WSL).

Solution
---------
My local man pages report that the used `gethostfromaddr()` and related functions are deprecated in favour of `getaddrinfo()`. Doing a relatively simple drop in replacement successfully sends packets (seen both in netcat and in a personal visualiser).

Diff of my personal fix (haven't attempted to make robust):
```diff
diff --git a/src/input_output/FGfdmSocket.cpp b/src/input_output/FGfdmSocket.cpp
index ba84668d..8668fab3 100644
--- a/src/input_output/FGfdmSocket.cpp
+++ b/src/input_output/FGfdmSocket.cpp
@@ -87,19 +87,12 @@ FGfdmSocket::FGfdmSocket(const string& address, int port, int protocol)
   if (!LoadWinSockDLL(debug_lvl)) return;
   #endif
 
-  if (!is_number(address)) {
-    host = gethostbyname(address.c_str());
-    if (host == NULL) {
-      cerr << "Could not get host net address by name..." << endl;
-      return;
-    }
-  } else {
-    unsigned long ip = inet_addr(address.c_str());
-    host = gethostbyaddr((char*)&ip, sizeof(ip), PF_INET);
-    if (host == NULL) {
-      cerr << "Could not get host net address by number..." << endl;
-      return;
-    }
+  struct addrinfo *addr;
+  int failure = getaddrinfo(address.c_str(), NULL, NULL, &addr);
+  if (failure) {
+    cerr << "Could not get host net address..." << endl;
+    cerr << gai_strerror(failure);
+    return;
   }
 
   if (protocol == ptUDP) {  //use udp protocol
@@ -116,10 +109,9 @@ FGfdmSocket::FGfdmSocket(const string& address, int port, int protocol)
   }
 
   if (sckt >= 0) {  // successful
-    memset(&scktName, 0, sizeof(struct sockaddr_in));
+    scktName = *(sockaddr_in *)addr->ai_addr;
     scktName.sin_family = AF_INET;
     scktName.sin_port = htons(port);
-    memcpy(&scktName.sin_addr, host->h_addr_list[0], host->h_length);
 
     int len = sizeof(struct sockaddr_in);
     if (connect(sckt, (struct sockaddr*)&scktName, len) == 0) {   // successful
```
**EDIT by** @bcoconni : inserted the diff inside the comment for easier reference.

**Comment by bcoconni** [comment]
Thanks @brisk0 for the detailed bug report.

Man pages indeed report that `gethostbyname` and `gethostbyaddr` are now obsolete (checked on Fedora 31). Now the question is: shall we continue to support `gethostbyname` and `gethostbyaddr` for platforms that might not have yet adopted the new functions `getaddrinfo` and `getnameinfo` ? Does someone know since when the new functions have been introduced ?

**Comment by bcoconni** [comment]
@brisk0 I have just pushed some code that replaces `gethostbyname` and `gethostbyaddr` by `getaddrinfo` as per your suggestion.

Please test and let me know if that fixes the problem you have reported.

**Comment by brisk0** [comment]
The push resolves the issue, cheers.
