### ISSUE TITLE
Aeromatic incidence input

### ISSUE THREAD

**Issue by NikolaiVChr** [JSBSim-Team/jsbsim#257]
When I input incidence 0 then it assumes I want it to make a guess of incidence instead of making an actual incidence of 0.

**Comment by Prepar3DGuy** [comment]
If you set 0 or leave it default than this code will set it to 2.
https://github.com/JSBSim-Team/jsbsim/blob/2f2398cbafc0fc4f14dc6157d1923548ec8804ba/utils/aeromatic%2B%2B/Aircraft.cpp#L318-L321

**Comment by ermarch** [comment]
Good point, it might be better to initialize it to something like -1 and test for that when setting it to 2.0

**Comment by seanmcleod** [comment]
@NikolaiVChr can we close this issue?

**Comment by NikolaiVChr** [comment]
yes
