### ISSUE TITLE
Jsbsim fdm feels better than datcom. Matlab as of now takes datcom..n jsbsim S funtion isnt performing well in R2015a..   Is there a way jsbsim fdm can be fitteded into aerospace blockset for better post processing ? 

### ISSUE THREAD

**Issue by kvnjonathan70** [JSBSim-Team/jsbsim#264]

**Comment by seanmcleod** [comment]
Take a look at this issue - https://github.com/JSBSim-Team/jsbsim/issues/70

**Comment by bcoconni** [comment]
> Take a look at this issue - #70

Indeed. I am closing this issue since it is a duplicate.
As @seanmcleod  mentioned, discussion about this topic should continue in issue #70.
