### ISSUE TITLE
Using the JSBSim Cpp API

### ISSUE THREAD

**Issue by Jaeyoung-Lim** [JSBSim-Team/jsbsim#286]
I am trying to use the jsbsim cpp api as explained in https://github.com/JSBSim-Team/jsbsim/blob/master/README.md#using-the-c-api and link it with my application through cmake. 

I have built jsbsim from source and installed it to my system on my default path.
However, I am not able to link my example application through cmake. 

Is there a standard way to link jsbsim on a 3rd party app using cmake? 

Any help regarding examples / information documented on how I can link my application to jsbsim through cmake would be appreciated.

**Comment by bcoconni** [comment]
Hi @Jaeyoung-Lim,

It's not available on all platforms but we have recently included an interface to`pkg-config` (commit 6401af3) which you could use to detect the headers and libraries location.

Given that JSBSim has no dependencies, I would not anticipate any difficulty but I might wrong. Could you please provide the error(s) that CMake reports when trying to link to JSBSim ? And I would be interested to know which platform you are using as well.

**Comment by bcoconni** [comment]
Hi @Jaeyoung-Lim,

Is your issue solved ? If you need further support, let us know. Otherwise, could you please confirm that this issue can be closed ?

Thanks.

**Comment by bcoconni** [comment]
Contact lost with issuer. Issue closed.
