### ISSUE TITLE
<floor> vs <integer>

### ISSUE THREAD

**Issue by NikolaiVChr** [JSBSim-Team/jsbsim#296]
Is there any difference?

**Comment by seanmcleod** [comment]
`<integer>` is implemented using `modf()` to return the integral part and `<floor>` is implemented using `floor()`

> floor - Rounds x downward, returning the largest integral value that is not greater than x.

Where they differ is with negative numbers, `floor(-2.1) = -3`

**Comment by NikolaiVChr** [comment]
Thanks
