### ISSUE TITLE
4 input variable 

### ISSUE THREAD

**Issue by kvnjonathan70** [JSBSim-Team/jsbsim#301]
Dear all, 
Good evening

In one condition i have 4 input variable from CFD data for pitch moment,
1. variation of alpha +-30 degree
2. variation of elevator deflection =+-30 degree
3. mach number is kept at 0.5
4. beta is kept at zero 

I have cm values for this table
JSBSim is limited to 3D data, i have to put only 3 variables, if i lose any one from beta and mach then FDM wouldnt be correct,   i have check previous example specially f16 and  ja37 aerodynamics, i couldnt find such implementation.

will it be correct if i declare either mach or beta property with its value inside the function where the table needs to be made such that this property value is exclusively for this table itself ?

Can anyone please suggest me some views regarding it.

**Comment by bcoconni** [comment]
Hi @kvnjonathan70,

One option is to define 3D tables for a fixed value of one parameter (`beta` for example) and then use `<interpolate1d>` to interpolate the results from the tables for the targeted value of `beta`.

An example of the usage of `<interpolate1d>` is (assuming the interpolation is a function of `test/input`)
https://github.com/JSBSim-Team/jsbsim/blob/8c0eb3789f3b1f00d5ca6e3b39de8266b4aaeb09/tests/function.xml#L99-L107
The function `<interpolate1d>` is a piece-wise linear interpolation. For our `beta`example, this means that the resulting function is like

<a href="https://www.codecogs.com/eqnedit.php?latex=f(\beta,&space;M,&space;\alpha,&space;\delta_e)=a(\alpha,&space;M,&space;\delta_e)\times\beta&plus;b(\alpha,&space;M,&space;\delta_e)" target="_blank"><img src="https://latex.codecogs.com/gif.latex?f(\beta,&space;M,&space;\alpha,&space;\delta_e)=a(\alpha,&space;M,&space;\delta_e)\times\beta&plus;b(\alpha,&space;M,&space;\delta_e)" title="f(\beta, M, \alpha, \delta_e)=a(\alpha, M, \delta_e)\times\beta+b(\alpha, M, \delta_e)" /></a>

**Comment by seanmcleod** [comment]
@kvnjonathan70 take a look at this https://sourceforge.net/p/jsbsim/mailman/message/31040616/ mailing list snippet which discusses how `interpolate1d` can be used when you have tables that are n-dimensional when n > 3. It has a couple of examples.

So for example you could go with something like the following:

```xml
<function name="pitchmoment">
  <interpolate1d>
    <p> velocities/mach </p>
    <v> 0.00 </v>  <table> ... 3D (alpha,beta,elevator) table definition ... </table>
    <v> 0.30 </v>  <table> ... 3D (alpha,beta,elevator) table definition ... </table>
    <v> 0.90 </v>  <table> ... 3D (alpha,beta,elevator) table definition ... </table>
  </interpolate1d>
</function>
```

I think we should grab Jon's description from the mailing list snippet and add it to our new documentation.

**Comment by kvnjonathan70** [comment]
Thanks, i tried it out, it was helpful :)
