### ISSUE TITLE
Possible out of bounds access on array in debug mode

### ISSUE THREAD

**Issue by sthagen** [JSBSim-Team/jsbsim#310]
In `src/models/flight_control/FGFilter.cpp` and when `(debug_lvl & 1) && from == 0` the array `C` with 7 slots will be accessed at index `7` and evaluate that value in a boolean context during the last iteration of the loop. cppcheck 1.82 warns on that one ... but maybe this is not a problem? It is a 1-based indexing on that array giving an extra slot never used at index `0` but, index `6` should be the largest one accessed.

```cpp
void FGFilter::Debug(int from)
{
  if (debug_lvl <= 0) return;

  if (debug_lvl & 1) { // Standard console startup message output
    if (from == 0) { // Constructor
      cout << "      INPUT: " << InputNodes[0]->GetName() << endl;

      for (int i=1; i <= 7; i++) {
        if (!C[i]) break;  // here access of C[7] in final iteration - test random value or seg fault?
// ...
```

**Comment by seanmcleod** [comment]
Yep it looks like the for loop will run off the end of the array.

https://github.com/JSBSim-Team/jsbsim/blob/a9fb5200c176953003253344f3ae5274897d4f6b/src/models/flight_control/FGFilter.h#L231

Please post a link to the relevant code as opposed to cutting and pasting, makes it easier and quicker for others to quickly jump to the code and browse around the relevant snippet. 

https://github.com/JSBSim-Team/jsbsim/blob/a9fb5200c176953003253344f3ae5274897d4f6b/src/models/flight_control/FGFilter.cpp#L207-L226

**Comment by seanmcleod** [comment]
@sthagen do you want to submit a pull request, or do you just want to report the issue and have one of the JSBSim developers fix it?

**Comment by sthagen** [comment]
I am happy to provide a pull request. Just wanted to be sure upfront that the project considers this an issue and indeed is open for contribution. Thanks for the fast and encouraging response (also on issue #309).

PS: From years at stackoverflow, I thought links would not be welcome, but with a versioning system under the hood the linkage I would prefer myself 😉 - thank you @seanmcleod for the hint.

**Comment by seanmcleod** [comment]
@sthagen yes we are definitely open for contributions.

Yep the github links are nice and smart ;-)
