### ISSUE TITLE
Error when running "pip install jsbsim"

### ISSUE THREAD

**Issue by StepLogic** [JSBSim-Team/jsbsim#326]
Hi I am new to python ,i am getting a whole lot of errors when i run "pip install jsbsim"
I am running python 3.6 

     ERROR: Command errored out with exit status 1:
     command: 'C:\Users\Gyaase Elvis\Anaconda3\envs\cpacscreator\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\GYAASE~1\\AppData\\Local\\Temp\\pip-install-zem_i66e\\jsbsim\\setup.py'"'"'; __file__='"'"'C:\\Users\\GYAASE~1\\AppData\\Local\\Temp\\pip-install-zem_i66e\\jsbsim\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\GYAASE~1\AppData\Local\Temp\pip-record-jgc3p8aw\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\Gyaase Elvis\Anaconda3\envs\cpacscreator\Include\jsbsim'
         cwd: C:\Users\GYAASE~1\AppData\Local\Temp\pip-install-zem_i66e\jsbsim\
    Complete output (40 lines):
    running install
    running build
    running build_ext
    skipping 'jsbsim.cpp' Cython extension (up-to-date)
    building 'jsbsim' extension
    creating build
    creating build\temp.win-amd64-3.6
    creating build\temp.win-amd64-3.6\Release
    creating build\temp.win-amd64-3.6\Release\src
    creating build\temp.win-amd64-3.6\Release\src\initialization
    creating build\temp.win-amd64-3.6\Release\src\models
    creating build\temp.win-amd64-3.6\Release\src\models\atmosphere
    creating build\temp.win-amd64-3.6\Release\src\models\flight_control
    creating build\temp.win-amd64-3.6\Release\src\models\propulsion
    creating build\temp.win-amd64-3.6\Release\src\math
    creating build\temp.win-amd64-3.6\Release\src\input_output
    creating build\temp.win-amd64-3.6\Release\src\simgear
    creating build\temp.win-amd64-3.6\Release\src\simgear\props
    creating build\temp.win-amd64-3.6\Release\src\simgear\xml
    creating build\temp.win-amd64-3.6\Release\src\simgear\magvar
    creating build\temp.win-amd64-3.6\Release\src\simgear\misc
    creating build\temp.win-amd64-3.6\Release\src\simgear\io
    creating build\temp.win-amd64-3.6\Release\src\simgear\io\iostreams
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\bin\Hostx64\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MT -Isrc "-IC:\Users\Gyaase Elvis\Anaconda3\envs\cpacscreator\include" "-IC:\Users\Gyaase Elvis\Anaconda3\envs\cpacscreator\include" "-IC:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\include" /EHsc /Tpjsbsim.cpp /Fobuild\temp.win-amd64-3.6\Release\jsbsim.obj -DJSBSIM_VERSION="1.0.0.dev1" -DHAVE_EXPAT_CONFIG_H -std=c++11
    cl : Command line warning D9002 : ignoring unknown option '-std=c++11'
    jsbsim.cpp
    jsbsim.cpp(11297): warning C4244: 'argument': conversion from 'double' to 'long', possible loss of data
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\bin\Hostx64\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MT -Isrc "-IC:\Users\Gyaase Elvis\Anaconda3\envs\cpacscreator\include" "-IC:\Users\Gyaase Elvis\Anaconda3\envs\cpacscreator\include" "-IC:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\include" /EHsc /Tpsrc/FGFDMExec.cpp /Fobuild\temp.win-amd64-3.6\Release\src/FGFDMExec.obj -DJSBSIM_VERSION="1.0.0.dev1" -DHAVE_EXPAT_CONFIG_H -std=c++11
    cl : Command line warning D9002 : ignoring unknown option '-std=c++11'
    FGFDMExec.cpp
    src/FGFDMExec.cpp(108): warning C4996: 'getenv': This function or variable may be unsafe. Consider using _dupenv_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
    src/FGFDMExec.cpp(134): warning C4996: 'getenv': This function or variable may be unsafe. Consider using _dupenv_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\bin\Hostx64\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MT -Isrc "-IC:\Users\Gyaase Elvis\Anaconda3\envs\cpacscreator\include" "-IC:\Users\Gyaase Elvis\Anaconda3\envs\cpacscreator\include" "-IC:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\include" /EHsc /Tpsrc/FGJSBBase.cpp /Fobuild\temp.win-amd64-3.6\Release\src/FGJSBBase.obj -DJSBSIM_VERSION="1.0.0.dev1" -DHAVE_EXPAT_CONFIG_H -std=c++11
    cl : Command line warning D9002 : ignoring unknown option '-std=c++11'
    FGJSBBase.cpp
    src/FGJSBBase.cpp(105): error C2440: 'initializing': cannot convert from 'double' to 'std::basic_string<char,std::char_traits<char>,std::allocator<char>>'
    src/FGJSBBase.cpp(105): note: No constructor could take the source type, or constructor overload resolution was ambiguous
    src/FGJSBBase.cpp(105): error C2143: syntax error: missing ';' before 'constant'
    src/FGJSBBase.cpp(105): error C2059: syntax error: 'constant'
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.26.28801\\bin\\Hostx64\\x64\\cl.exe' failed with exit status 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\Gyaase Elvis\Anaconda3\envs\cpacscreator\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\GYAASE~1\\AppData\\Local\\Temp\\pip-install-zem_i66e\\jsbsim\\setup.py'"'"'; __file__='"'"'C:\\Users\\GYAASE~1\\AppData\\Local\\Temp\\pip-install-zem_i66e\\jsbsim\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\GYAASE~1\AppData\Local\Temp\pip-record-jgc3p8aw\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\Gyaase Elvis\Anaconda3\envs\cpacscreator\Include\jsbsim' Check the logs for full command output.

**Comment by bcoconni** [comment]
Yes, this is a known issue about our packages on PyPI. Fortunately this can be worked around by using the Python wheel packages from our releases on GitHub:
```bash
pip install jsbsim --no-index -f https://github.com/JSBSim-Team/jsbsim/releases/tag/Windows-MSVC/JJSBSim-1.1.0.dev1-92-cp36-cp36m-win_amd64.whl
```
In the example above, the package for Python 3.6 will be installed. If you are using another version of Python, you might need to change the file name:

| Python version | File name for Windows |
|-|-|
| 3.6 | JSBSim-1.1.0.dev1-92-cp36-cp36m-win_amd64.whl |
| 3.7 | JSBSim-1.1.0.dev1-92-cp37-cp37m-win_amd64.whl |
| 3.8 | JSBSim-1.1.0.dev1-92-cp38-cp38-win_amd64.whl |

Let us know if that works !

**Comment by StepLogic** [comment]
thanks
