### ISSUE TITLE
How does JSBSim transfer heading error into control face deflection in autopilot?

### ISSUE THREAD

**Issue by theorynice** [JSBSim-Team/jsbsim#343]
As mentioned above, the airctaft can caculate state variable by the motion equation. But in autopilot, how does JSBSim transfer the heading error into Aileron deflection？ what I think is that, the heading error was feed into PID and then we get a scalar value as the aileron deflection cmd.  Then the deflection was substitute into motion equation again to caculate the next time actual heading angle and compare with the desired heading angle，is it？

**Comment by seanmcleod** [comment]
Yes.

**Comment by theorynice** [comment]
Thanks very much. Where in source code(or in which class) can I find the relevant code?

**Comment by seanmcleod** [comment]
There isn't any specific autopilot source code in the JSBSim source code.

Autopilots are implemented in the xml files for the aircraft. Take a look in the JSBSim Reference Manual, there are a bunch of examples of autopilot implementations.

http://jsbsim.sourceforge.net/JSBSimReferenceManual.pdf

**Comment by theorynice** [comment]
> There isn't any specific autopilot source code in the JSBSim source code.
> 
> Autopilots are implemented in the xml files for the aircraft. Take a look in the JSBSim Reference Manual, there are a bunch of examples of autopilot implementations.
> 
> http://jsbsim.sourceforge.net/JSBSimReferenceManual.pdf

OK, thank you very much!

**Comment by bcoconni** [comment]
@theorynice, shall we consider this item closed or do you need further help ?
