### ISSUE TITLE
Scheduled gain

### ISSUE THREAD

**Issue by brats2017** [JSBSim-Team/jsbsim#344]
Hello all,

I have a question. In the X15 aircraft XML file, there is a scheduled gain. Do you know how we can obtain a scheduled gain for an aircraft in JSBSim? I know it is possible to design and implement gain-scheduled controllers with MATLAB and Simulink. Is it possible to design it in JSBSim?

Thanks in advance.

**Comment by seanmcleod** [comment]
JSBSim doesn't have any facilities for calculating the gain values, you would need to use other software like MATLAB etc. to help you calculate the gain values to use in your scheduled gain which you could then plug into JSBSim as you've seen in the X-15 example.

**Comment by maedehmohammadi** [comment]
Thank you so much for your quick response.

**Comment by maedehmohammadi** [comment]
For my own aircraft, it is complex and time-consuming to simulate it in MATLAB to obtain scheduled-gain. Do you think can I calculate scheduled-gain using [MATLAB-JSBSim](https://github.com/podhrmic/JSBSim-Matlab)?
Thanks in advance @seanmcleod.

**Comment by seanmcleod** [comment]
I'm aware of the MATLAB-JSBSim integration but I've never used it myself. Take a look at the following issue which has some discussion of trying to get it to work with more recent versions of Matlab etc.

https://github.com/JSBSim-Team/jsbsim/issues/70

**Comment by maedehmohammadi** [comment]
Thank you so much for your response @seanmcleod.

**Comment by bcoconni** [comment]
@brats2017, shall we consider this item closed or do you need further help ?

**Comment by brats2017** [comment]
Thank you so much. My problem has been solved with your help.
