### ISSUE TITLE
c310.xml file 

### ISSUE THREAD

**Issue by brats2017** [JSBSim-Team/jsbsim#345]
Hello all,
I am running the **c3101.xml** file. When I change the PID controller gains, the outputs do not change.
For example:

>     <property value="50.0"> ap/roll-pid-kp </property>
>     <property value="5"> ap/roll-pid-ki </property>
>     <property value="17.0"> ap/roll-pid-kd </property> 

The phi is as follow: 
![image](https://user-images.githubusercontent.com/65332612/99565205-610e6300-2999-11eb-9041-79c0107177a5.png)

When I change the PID controller gains to 0 or other values, the phi does not change. Why?
Also, for every change that I apply in the c310ap.xml file, the outputs (phi, velocity, and other property) do not change.
Thanks in advance.

**Comment by brats2017** [comment]
Thank you so much for your detailed answer @bcoconni. It works now.

**Comment by bcoconni** [comment]
Glad it helps !
