### ISSUE TITLE
How should the product of inertia be computed?

### ISSUE THREAD

**Issue by aarondewindt** [JSBSim-Team/jsbsim#440]
On some sources such as "Aircraft Control and Simulation: Dynamics, Controls Design, and Autonomous Systems" by "Brian L. Stevens", the product moment of inertia are computed with.

![eq1](https://user-images.githubusercontent.com/7420823/121930746-0082b100-cd43-11eb-9785-296beccdf021.gif)

However on some other sources the product of inertia is computed the equation shown below. So this would be the value in the inertia tensor.

![eq2](https://user-images.githubusercontent.com/7420823/121930890-3162e600-cd43-11eb-9d0c-943e9c6357fd.gif)

After looking through the JSBSim source code we think we should fill in values calculated by the second equation. Is this the case?

**Comment by seanmcleod** [comment]
See the following:

https://github.com/JSBSim-Team/jsbsim/blob/a35be5ce6f7d7ca0ef9a11a62563e54d769bc4f4/src/models/FGMassBalance.h#L68-L71

Which was updated as part of the following commit - https://github.com/JSBSim-Team/jsbsim/commit/03763374fcd688bdcf9faf6164106a68f8ba3c0b#diff-ef28318d289aee0dd2e968ada735838f3e7ad8daf7da1eaea2448ed27ec56b4a

With further info in this earlier issue - https://github.com/JSBSim-Team/jsbsim/issues/125

**Comment by aarondewindt** [comment]
@seanmcleod Thanks!!
