### ISSUE TITLE
JSBSIM Compile & Build / libtool not found

### ISSUE THREAD

**Issue by doughodson** [JSBSim-Team/jsbsim#465]
### Discussed in https://github.com/JSBSim-Team/jsbsim/discussions/464

<div type='discussions-op-text'>

<sup>Originally posted by **doughodson** July  2, 2021</sup>
I just tried to compile JSBSIM 1.1.6 using configure.... it doesn't locate libtool on my system, and indicates that it needs to be installed (or newer) -- I'm wondering if what I have is too new, and it not being located properly. I ended up installing and using cmake, which worked.

BTW, I'm glad to see interfaces to Julia!!! Thanks,
Doug
</div>

**Comment by bcoconni** [comment]
@doughodson Please don't duplicate discussion with an issue.
