### ISSUE TITLE
Multiprocessing JSBSim with Python

### ISSUE THREAD

**Issue by sr71684** [JSBSim-Team/jsbsim#515]
When attempting to pass an FGFDMExec instance into a python processing pool, JSBSim returns the following error:
```
  File "stringsource", line 2, in jsbsim.FGFDMExec.__reduce_cython__
TypeError: no default __reduce__ due to non-trivial __cinit__
```
This happens because FGFDMExec can't be trivially pickled. 

Does there exist a way to pickle FGFDMExec such that the above error is avoided? 

**Minimum working example:**

```python
import os
from multiprocessing import Pool

import jsbsim


def make_fdm():
    fdm = jsbsim.FGFDMExec(root_dir=os.path.abspath('/home/jsbsim'))
    fdm.set_debug_level(0)
    time_step = 0
    fdm.load_model("c172p")
    fdm.set_dt(1.0 / 6.0)
    return fdm


def run(fdm):
    # do fdm stuff here
    return fdm

if __name__ == "__main__":
    n_sims = 10
    n_threads = 4
    envs = [make_fdm() for id in range(n_sims)]

    p = Pool(n_threads)
    results = p.map(run, envs)
```

**Environment**
 - OS: Ubuntu 20.04 LTS
 - JSBSim version: v1.1.10
 - Language: Python

**Comment by bcoconni** [comment]
Hi @sr71684,

Indeed [Cython extension types can't be pickled when they contain the `__cinit__` method](https://cython.readthedocs.io/en/latest/src/userguide/extension_types.html#controlling-pickling).

So your best course of action is to create a new Python class that inherits from `FGFDMExec` and that implements the `__reduce__` method:
```python
class PickleFDMExec(jsbsim.FGFDMExec):
  def load_model(self, model_name):
    self.model_name = model_name  # Store a copy of the model name
    jsbsim.FGFDMExec.load_model(self, model_name)
  def __reduce__(self):
    return (rebuild, self.get_root_dir(), self.model_name, self.get_delta_t())

# Tells pickle how to rebuild the FDM from the reduced data.
def rebuild(root_dir, model_name, dt):
  fdm = jsbsim.FGFDMExec(root=root_dir)
  fdm.load_model(model_name)
  fdm.set_dt(dt)
  return fdm
```
