### ISSUE TITLE
Prefer PROJECT_SOURCE_DIR over CMAKE_SOURCE_DIR

### ISSUE THREAD

**Issue by Aaron-SP** [JSBSim-Team/jsbsim#684]
When bundling JSBSIM as an external project using CMAKE FetchContent, JSBSIM is not configured because it uses CMAKE_SOURCE_DIR instead of PROJECT_SOURCE_DIR.

[CMAKE Issue Explained](https://stackoverflow.com/questions/32028667/are-cmake-source-dir-and-project-source-dir-the-same-in-cmake)

I've made a fork with this change at [repo](https://github.com/Aaron-SP/jsbsim).

Does it make sense to make this change to expand packaging capabilities of JSBSim with CMAKE?

**Comment by bcoconni** [comment]
Thanks for reporting this issue.
Would you mind submitting a pull request from your repo ?

**Comment by Aaron-SP** [comment]
I have opened a pull request [here](https://github.com/JSBSim-Team/jsbsim/pull/689). This fixes my issue but I did not check building the extra modules such as Python etc. We might want to double check that any files that code generate CMAKE are also updated, not sure.

**Comment by bcoconni** [comment]
Your pull request has been merged.
Thanks for your contribution 👍
