### ISSUE TITLE
pkgconfig .pc file has wrong include path

### ISSUE THREAD

**Issue by vranki** [JSBSim-Team/jsbsim#770]
The pkgconfig .pc file shipped with development debian package contains: includedir=/usr/local/include but JSBSim is installed in /usr/include.

This causes build using pkgconfig to fail. Workaround is to set includepath manually, but this should be fixed in .pc file.

**Comment by bcoconni** [comment]
Thanks for reporting the bug @vranki.
This should now be fixed in the `master` branch (commit c4970ed343c9e4b49532bd168a5e3626e8466e6e)

**Comment by vranki** [comment]
Thanks for the quick fix, LGTM! The issue can be closed unless you want to keep it open until release.

**Comment by bcoconni** [comment]
JSBSim v1.1.13 has just been released and contains the fix.
Issue closed.
