### ISSUE TITLE
Online Python API documentation not working

### ISSUE THREAD

**Issue by Dobid** [JSBSim-Team/jsbsim#805]
Hello,
I'm facing the exact same issue as in [#373](https://github.com/JSBSim-Team/jsbsim/issues/373) : when I click on a class to see the docs, everything is blank. The issue seemed to be resolved back a year ago, but it seems to have resurfaced.

![image](https://user-images.githubusercontent.com/36502022/211028202-9ed0a5b8-b335-4945-b250-09708c19c706.png)

Thanks in advance !

**Comment by Dobid** [comment]
Up !

**Comment by bcoconni** [comment]
Thanks @Dobid for pointing this out.
I can reproduce the issue and I'll try to address this in the coming days.

**Comment by bcoconni** [comment]
This is now fixed [FGFDMExec](https://jsbsim-team.github.io/jsbsim/python/FGFDMExec.html) is functional again.

**Comment by Dobid** [comment]
Great, every section is now displaying something ! I'm closing the issue. Thank you very much.
