### ISSUE TITLE
JSBSim Unreal throws an Exception few seconds after/during takeoff

### ISSUE THREAD

**Issue by demonixis** [JSBSim-Team/jsbsim#876]
**I'm submitting a ...**
  - [X] bug report
  - [ ] feature request
  - [ ] support request => **Please do not submit support request here**, see note at the top of this template.

**Describe the issue**
With Unreal Engine 5.1.1, when I start the TakeOff process, after few seconds, the application throws an exception, resulting many NaN. The controlled pawn is destroyed and the editor freezes.

**What is the current behavior?**
After few hours of debug, here is what I've found

An Exception is thrown.

`JSBSimMovementComponent::GetAGLevel`
	- StartECEFLocation NaN
	- FVector ECEFLocation = FVector(location(1), location(2), location(3)) * FEET_TO_METER; // NaN

If you take a look at `double UEGroundCallback::GetAGLevel(const FGLocation& location, FGLocation& contact, FGColumnVector3& normal, FGColumnVector3& vel, FGColumnVector3& angularVel) const`

Actually the `location` variable already contains NaNs
	
In `JSBSimMovementComponent::Tick` 
	- Aircraft.LocalEulerAngles X, Y, NaN
	- AircraftState.ECEFLocation NaN
	- Exec
	    - GroundReactions.In = NaN
	    - Aircraft.In
		- Airforce +Inf, NaN, -Inf
		- AeroForce +Inf, Nan, -Inf
		- vMovements NaN, NaN, NaN
		- vForces = +Inf, NaN, -Inf 

**What is the expected behavior?**
The expected behaviour is to not have an exception and be able to fly.

**Please tell us about your environment:**
 - OS: Windows 11 + Unreal Engine 5.1.1
 - JSBSim version: Latest
 - Language: C++

**Comment by gallonmate** [comment]
I would start again with UE5 reference demo project and slowly introduce whatever changes you added to help find why the crash happens: The aircraft used, the location, the meshes used for ground, geo-reference settings, etc.
