### ISSUE TITLE
Crashes after adding an xml path to a component in the engine

### ISSUE THREAD

**Issue by lhy0108** [JSBSim-Team/jsbsim#911]
![1](https://github.com/JSBSim-Team/jsbsim/assets/113595027/668d26b5-ca0e-4c2d-bc40-d31f7e10f9e1)
![2](https://github.com/JSBSim-Team/jsbsim/assets/113595027/e40d6305-83ef-4d61-989c-fd7d8895b75d)
![3](https://github.com/JSBSim-Team/jsbsim/assets/113595027/d0ffefb4-d1d5-43ae-87f2-3d8da41f62db)
![4](https://github.com/JSBSim-Team/jsbsim/assets/113595027/4576691d-ae29-4300-9ac5-fe4937c0892a)

**What is the reason?**

**Comment by lhy0108** [comment]
**What is the reason?**

**Comment by gallonmate** [comment]
The title of the discussion says "Crashes after adding an xml path to a component in the engine" but the post shows nothing related. Can you please describe or show what changes you made that lead to the crash.

Also you started a duplicate Issue and Discussion. Please use one or the other, not both.

**Comment by lhy0108** [comment]
Hello, crash occurred when I ran the engine after generating the JSBSimForUnreal.sln file and the JSBSim component could not read the xml file

**Comment by lhy0108** [comment]
When my Blueprint role uses the JSBSimMovement component, it crashes because it can't read the xml file

**Comment by gallonmate** [comment]
Well if you didn't change anything in the original project demo file, then it shouldn't crash. 
Make sure that JSBSimForUnreal.sln was built as Release and not Debug.

**Comment by lhy0108** [comment]
You can see in the image above that after I generated JSBSimForUnreal.sln, it automatically added the JSBSim file, but it still crashed when I used UE to read the aircraft model

**Comment by lhy0108** [comment]
Oh, thank you. I tried to rebuild  JSBSimForUnreal.sln

**Comment by lhy0108** [comment]
The problem has been solved. Thank you for your patient reply

**Comment by gallonmate** [comment]
Can you let us know what solved the issue? Was the problem with Debug build and Release solved it?
If so, it's a known issue and I'm working to fix the Debug build in the near future.

**Comment by bcoconni** [comment]
@lhy0108 
> The problem has been solved. Thank you for your patient reply

Your issue may be resolved however patience is not a virtue that you've displayed as you've posted 5 messages in less than 24h asking the exact same question:
* [May 10th, 2023, 10:19UTC](https://github.com/JSBSim-Team/jsbsim/issues/626#issuecomment-1541876385) Issue #626
* [May 11th, 2023, 07:56UTC](https://github.com/JSBSim-Team/jsbsim/discussions/910#discussion-5184213)
* May 11th, 2023, 07:59UTC (deleted by yourself)
* [May 11th, 2023, 08:01UTC](https://github.com/JSBSim-Team/jsbsim/issues/911#issue-1705281258)
* [May 11th, 2023, 08:40UTC](https://github.com/JSBSim-Team/jsbsim/issues/911#issuecomment-1543582941)

And would like to stress the fact that the 4 last messages have been posted in less than 45 minutes. This is message bombing (and spamming our mailboxes) which by all measure is extremely rude. Not to mention that you've disregarded the caution messages that request not to use issues for support requests.

For your information, JSBSim is maintained by a small team of volunteers on their free time so we cannot be 24/7 online responding questions and support requests. So we would appreciate very much that in the future you use wisely the communication tools that are provided by the project and most of all be patient.

Thanks.
