### ISSUE TITLE
Building for Unreal 5 on Linux not working

### ISSUE THREAD

**Issue by RomanBapst** [JSBSim-Team/jsbsim#963]
**I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request => **Please do not submit support request here**, see note at the top of this template.

**Describe the issue**
I tried to build an run JSBSim for Unreal 5.3.0 on Ubuntu 20.04. When launching `UnrealEditor` it complained about `libJSBSim.so` not being found. I saw on a recent PR that support for Linux might not quite be there and that there supposedly are some linking issues.

In my case I was able to resolve the issue by adding the path to  `libJSBSim.so` to `LD_LIBRARY_PATH`.

Just wanted to report this in case it's helpful.

**Comment by RomanBapst** [comment]
![image (14)](https://github.com/JSBSim-Team/jsbsim/assets/7610489/3c23bd59-c150-4d65-8f07-13e851d7d80d)

**Comment by bcoconni** [comment]
Hi @RomanBapst, thanks for reporting the issue.

@demonixis could you please comment on this ?

**Comment by demonixis** [comment]
Do you compile it using clang? Can you share the logs please?

**Comment by RomanBapst** [comment]
@demonixis Yes, I was using clang. Do you need anything verbose turned on or just the standard logs?

**Comment by demonixis** [comment]
For a reason I don't understand, cmake produces 3 files

- libJSBSim.so(Symlink to file)
- libJSBSim.so.1(Symlink to file)
- libJSBSim.so.1.2.0.dev1

You've to copy those 3 files for Unreal to load properly. Renaming libJSBSim.so.1.2.dev1 into libJSBSim.so doesn't work.
I'll update the README to reflect that.

**Comment by demonixis** [comment]
Hey, any news about this?

**Comment by bcoconni** [comment]
This issue is being closed because the issuer is not responding.
